/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    fontFamily: {
      sans: ['"Fira Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      mono: ['"Fira Code"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
    },
    fontSize: {
      caption: ['12px', { lineHeight: '16px' }],
      sm: ['14px', { lineHeight: '20px' }],
      base: ['16px', { lineHeight: '24px' }],
      lg: ['18px', { lineHeight: '28px' }],
      xl: ['24px', { lineHeight: '32px' }],
      '2xl': ['32px', { lineHeight: '40px' }],
    },
    spacing: {
      0: '0px',
      xs: '2px',
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
      '2xl': '24px',
      '3xl': '32px',
      px: '1px',
    },
    borderRadius: {
      none: '0px',
      sm: '4px',
      DEFAULT: '4px',
      md: '6px',
      lg: '8px',
      full: '9999px',
    },
    boxShadow: {
      none: 'none',
      sm: '0 1px 2px rgba(0,0,0,.05)',
      md: '0 4px 6px rgba(0,0,0,.1)',
      lg: '0 10px 15px rgba(0,0,0,.1)',
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: '#FFFFFF',
      bg: 'var(--color-bg)',
      surface: 'var(--color-surface)',
      'surface-elevated': 'var(--color-surface-elevated)',
      muted: 'var(--color-muted)',
      border: 'var(--color-border)',
      'border-strong': 'var(--color-border-strong)',
      'text-primary': 'var(--color-text-primary)',
      'text-secondary': 'var(--color-text-secondary)',
      'text-muted': 'var(--color-text-muted)',
      primary: {
        DEFAULT: 'var(--color-primary)',
        hover: 'var(--color-primary-hover)',
      },
      'on-primary': 'var(--color-on-primary)',
      secondary: 'var(--color-secondary)',
      ring: 'var(--color-ring)',
      info: 'var(--color-info)',
      good: { DEFAULT: 'var(--color-good)', bg: 'var(--color-good-bg)' },
      monitor: { DEFAULT: 'var(--color-monitor)', bg: 'var(--color-monitor-bg)' },
      critical: { DEFAULT: 'var(--color-critical)', bg: 'var(--color-critical-bg)' },
      chart: {
        1: 'var(--chart-cat-1)',
        2: 'var(--chart-cat-2)',
        3: 'var(--chart-cat-3)',
      },
      seq: {
        1: 'var(--chart-seq-1)',
        2: 'var(--chart-seq-2)',
        3: 'var(--chart-seq-3)',
        4: 'var(--chart-seq-4)',
      },
    },
    extend: {
      transitionDuration: {
        DEFAULT: '200ms',
      },
    },
  },
  plugins: [],
}
